### ISSUE TITLE
I have a error about type

### ISSUE THREAD

**Issue by maledicente** [nateemma/strategies#7]
model not found (/freqtrade/user_data/treinoscheckpoint.h5)...
    data:[0:24608] train:[4921:24597] train_result:[4933:24609] test:[0:4918] test_result:[12:4930] 
2023-01-25 15:09:04,217 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1335, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1236, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1203, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1203, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1221, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/Predict_LSTM.py", line 289, in populate_indicators
    dataframe = self.train_model(dataframe, self.curr_pair)
  File "/freqtrade/user_data/strategies/Predict_LSTM.py", line 461, in train_model
    df_tensor = self.dataframeUtils.df_to_tensor(df_norm, self.seq_len)
  File "/freqtrade/user_data/strategies/DataframeUtils.py", line 492, in df_to_tensor
    tensor_arr[row][seq] = data[src_row]
TypeError: float() argument must be a string or a real number, not 'Timestamp'
ERROR: 1

**Comment by nateemma** [comment]
Hi,

  sorry, just saw your email.

This error means that you are passing in a DataFrame that has not been
normalized - the default 'date' column is text.

Also, that is an old version that I should have removed. The newer version
is NNPredict.py
As an aside, there is a family of related strategies called NNPredict_*.py,
and NNPredict.py is the base class (and uses an LSTM model as default).

Hope that helps,

Cheers,

Phil

**Comment by maledicente** [comment]
Ty
